# For Java 14, try this
FROM adoptopenjdk/openjdk14:alpine-jre

LABEL maintainer=" Mesut Saritas <mesut.saritas@turkcell.com.tr>"


# Refer to Maven build -> finalName
ARG JAR_FILE=target/*.jar

# cd /opt/app
WORKDIR /opt/app

# cp target/docker-spring-boot.jar /opt/app/app.jar
COPY ${JAR_FILE} app.jar

# java -jar /opt/app/app.jar
ENTRYPOINT ["java","-jar","app.jar"]