  

version: '3'

services:
  docker-spring-boot:
    image: docker-spring-boot
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/spring-boot
    ports:
      - "8080:8080"